version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      - db

  db:
    image: oscarfonts/h2
    ports:
      - "1521:1521"
      - "81:81"
    environment:
      H2_OPTIONS: "-ifNotExists"
